before_install: eval $(curl https://travis-perl.github.io/init) --auto
dist: xenial
language: perl
perl:
  # Oldest we support.
  - "5.6"
  # Travis has these, nice & quick.
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  # Latest & greatest.
  - "5.30"
  - "dev"
